INSERT INTO hotel (name, city, amenities, photos, address, phone_number, email, location,
                   active)
VALUES ('Shyam', 'Madhubani', '["WiFi","Parking","Pool"]',
        '["https://tse1.mm.bing.net/th/id/OIP.FtudhIBH-HYhxMpS4TU-sAHaE8?pid=Api"]',
        'Vrindavan',
        '123',
        'email@example.com',
        'Location',
        FALSE);

INSERT INTO room (base_price, capacity, total_count, type, hotel_id, amenities, photos)
VALUES ('2000.00', 2, 10, 'AC', 1, '["WiFi","Parking","Pool"]',
        '["https://tse1.mm.bing.net/th/id/OIP.FtudhIBH-HYhxMpS4TU-sAHaE8?pid=Api"]'),
       ('1800.00', 3, 8, 'Non-AC', 1, '["WiFi","Parking"]',
        '["https://tse1.mm.bing.net/th/id/OIP.Zis2cXdglxbZemS3QNsdZQHaE8?pid=Api"]'),
       ('2500.00', 2, 5, 'AC', 1, '["WiFi","Pool"]',
        '["https://tse1.mm.bing.net/th/id/OIP.NEPl1oV2pX3UgOLBqFSJQwHaE8?pid=Api"]'),
       ('3000.00', 4, 2, 'AC', 1, '["WiFi","Parking","Pool","Gym"]',
        '["https://tse1.mm.bing.net/th/id/OIP.dndFJ-rO1uVHx-ICH1WfzAHaE8?pid=Api"]'),
       ('2200.00', 2, 12, 'Non-AC', 1, '["WiFi","Pool"]',
        '["https://tse1.mm.bing.net/th/id/OIP.FtudhIBH-HYhxMpS4TU-sAHaE8?pid=Api"]'),
       ('2400.00', 3, 6, 'AC', 1, '["WiFi","Parking"]',
        '["https://tse1.mm.bing.net/th/id/OIP.Zis2cXdglxbZemS3QNsdZQHaE8?pid=Api"]'),
       ('2100.00', 2, 5, 'AC', 1, '["WiFi","Pool"]',
        '["https://tse1.mm.bing.net/th/id/OIP.NEPl1oV2pX3UgOLBqFSJQwHaE8?pid=Api"]'),
       ('2700.00', 4, 3, 'AC', 1, '["WiFi","Parking","Pool","Gym","Spa"]',
        '["https://tse1.mm.bing.net/th/id/OIP.dndFJ-rO1uVHx-ICH1WfzAHaE8?pid=Api"]'),
       ('1900.00', 2, 8, 'Non-AC', 1, '["WiFi"]',
        '["https://tse1.mm.bing.net/th/id/OIP.FtudhIBH-HYhxMpS4TU-sAHaE8?pid=Api"]'),
       ('2300.00', 3, 4, 'AC', 1, '["WiFi","Parking"]',
        '["https://tse1.mm.bing.net/th/id/OIP.Zis2cXdglxbZemS3QNsdZQHaE8?pid=Api"]'),
       ('2600.00', 2, 5, 'AC', 1, '["WiFi","Pool"]',
        '["https://tse1.mm.bing.net/th/id/OIP.NEPl1oV2pX3UgOLBqFSJQwHaE8?pid=Api"]'),
       ('2800.00', 4, 2, 'AC', 1, '["WiFi","Parking","Pool"]',
        '["https://tse1.mm.bing.net/th/id/OIP.dndFJ-rO1uVHx-ICH1WfzAHaE8?pid=Api"]'),
       ('2000.00', 2, 10, 'AC', 1, '["WiFi","Parking"]',
        '["https://tse1.mm.bing.net/th/id/OIP.FtudhIBH-HYhxMpS4TU-sAHaE8?pid=Api"]'),
       ('2200.00', 3, 6, 'Non-AC', 1, '["WiFi","Pool"]',
        '["https://tse1.mm.bing.net/th/id/OIP.Zis2cXdglxbZemS3QNsdZQHaE8?pid=Api"]'),
       ('2400.00', 2, 4, 'AC', 1, '["WiFi","Parking","Pool"]',
        '["https://tse1.mm.bing.net/th/id/OIP.NEPl1oV2pX3UgOLBqFSJQwHaE8?pid=Api"]'),
       ('2600.00', 4, 3, 'AC', 1, '["WiFi","Pool","Gym"]',
        '["https://tse1.mm.bing.net/th/id/OIP.dndFJ-rO1uVHx-ICH1WfzAHaE8?pid=Api"]'),
       ('2100.00', 2, 5, 'Non-AC', 1, '["WiFi"]',
        '["https://tse1.mm.bing.net/th/id/OIP.FtudhIBH-HYhxMpS4TU-sAHaE8?pid=Api"]'),
       ('2300.00', 3, 4, 'AC', 1, '["WiFi","Parking"]',
        '["https://tse1.mm.bing.net/th/id/OIP.Zis2cXdglxbZemS3QNsdZQHaE8?pid=Api"]'),
       ('2500.00', 2, 6, 'AC', 1, '["WiFi","Pool"]',
        '["https://tse1.mm.bing.net/th/id/OIP.NEPl1oV2pX3UgOLBqFSJQwHaE8?pid=Api"]'),
       ('2700.00', 4, 3, 'AC', 1, '["WiFi","Parking","Pool"]',
        '["https://tse1.mm.bing.net/th/id/OIP.dndFJ-rO1uVHx-ICH1WfzAHaE8?pid=Api"]'),
       ('2000.00', 2, 5, 'Non-AC', 1, '["WiFi"]',
        '["https://tse1.mm.bing.net/th/id/OIP.FtudhIBH-HYhxMpS4TU-sAHaE8?pid=Api"]'),
       ('2100.00', 3, 6, 'AC', 1, '["WiFi","Pool","Gym"]',
        '["https://tse1.mm.bing.net/th/id/OIP.NEPl1oV2pX3UgOLBqFSJQwHaE8?pid=Api"]');
